openapi: "3.0.0"
info:
  version: 0.1.0
  title: WaCoDiS Data Access
  description: |
    The API for the WaCoDiS Data Access
  termsOfService: https://wacodis.fbg-hsbo.de/
  contact:
    name: WaCoDiS Dev Team
    email: sebastian.drost@hs-bochum.de
    url: https://github.com/WaCoDiS
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost/dataAccess
paths: {}
components:
  schemas:
    AbstractDataEnvelope:
      required:
        - sourceType
      discriminator:
        propertyName: sourceType
      properties:
        sourceType:
          type: string
          enum: [SensorWebDataEnvelope, CopernicusDataEnvelope, GdiDeDataEnvelope]
          description: |
            shall be used to determine the responsible data backend
        areaOfInterest:
          type: object
          required:
            - extent 
          properties:
            extent:
              description: |
                the coordinates, using EPSG:4326, (in analogy to GeoJSON bbox) in the order
                "southwesterly point followed by more northeasterly point". Schema
                is [minLon, minLat, maxLon, maxLat]
              type: array
              minItems: 4
              maxItems: 4
              items: 
                type: number
                format: float
                minimum: -180.0
                maximum: 180.0
        timeFrame:
          type: object
          description:
            time frame the dataset covers
          required:
            - startTime
            - endTime
          properties:
            startTime:
              type: string
              format: date-time
              description: |
                the beginning of the time frame
            endTime:
              type: string
              format: date-time
              description: |
                the ending of the time frame
          format: date-time
        created:
          type: string
          format: date-time
          description: |
            time on which the dataset was created or became available
        modified:
          type: string
          format: date-time
          description: |
            time on which the dataset was modified last
    SensorWebDataEnvelope:
      allOf:
        - $ref: '#/components/schemas/AbstractDataEnvelope'
        - required:
          - offering
          - featureOfInterest
          - observedProperty
          - procedure
          - serviceUrl
          properties:
            serviceUrl:
              type: string
            offering:
              type: string
            featureOfInterest:
              type: string
            observedProperty:
              type: string
            procedure:
              type: string
    CopernicusDataEnvelope:
      allOf:
        - $ref: '#/components/schemas/AbstractDataEnvelope'
        - required:
          - datasetId
          - satellite
          - cloudCoverage
          - portal
          properties:
            datasetId:
              description:
                the id of the
            satellite:
              type: string
              enum: [sentinel-1, sentinel-2, sentinel-3]
            cloudCoverage:
              type: number
              format: float
            portal:
              type: string
              enum: [Code-DE, Sentinel-Hub]
    GdiDeDataEnvelope:
      allOf:
        - $ref: '#/components/schemas/AbstractDataEnvelope'
        - required:
          - recordRefId
          properties:
            catalougeUrl:
              description: |
                URL of the GDI-DE catalogue
              type: string
            recordRefId:
              description: |
                the id of the dataset within the GDI-DE catalogue
              type: string