openapi: "3.0.0"
info:
  version: 0.1.0
  title: WaCoDiS DataAccess API
  description: |
    The API for the WaCoDiS Data Access
  termsOfService: https://wacodis.fbg-hsbo.de/
  contact:
    name: WaCoDiS Dev Team
    email: arne.vogt@hs-bochum.de
    url: https://github.com/WaCoDiS
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost/dataAccess
paths:
  /resources/search:
    post:
      description: |
        searches for specific spatial data
      operationId: searchResources
      requestBody:
        description: |
          search criteria
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataAccessResourceSearchBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: |
                  return a map containing matching Resources for each SubsetDefinition
                  (key SubsetDefinition Identifier, value Array of matching Resources)
                type: object
                additionalProperties:
                  description: |
                    empty array if no matching resource was found
                  type: array
                  items:
                    $ref: '#/components/schemas/AbstractResource'
        '500':
          $ref: '#/components/responses/defaultError'
  /dataenvelopes:
    post:
      description: |
        create DataEnvelope
      operationId: createResource
      requestBody:
        description: |
          DataEnvelope to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AbstractDataEnvelope'
      responses:
        '201':
          description: |
            DataEnvelope created
          content:
            application/json:
              schema:
                description: |
                  created DataEnvelope including indentifier
                $ref: '#/components/schemas/AbstractDataEnvelope'
        '500':
          $ref: '#/components/responses/defaultError'
  /dataenvelopes/{id}:
    get: 
      description: |
        retrieve DataEnvelope by Id
      operationId: retrieveDataEnvelope
      parameters:
        - name: id
          in: path
          description: |
            ID of DataEnvelope to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: resource available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AbstractDataEnvelope'
        '404':
          description: |
            no DataEnvelope available for the given id
        '500':
          $ref: '#/components/responses/defaultError'
    put:
      description: |
        update DataEnvelope
      operationId: modifyDataEnvelope
      parameters:
        - name: id
          in: path
          description: |
            ID of DataEnvelope to be updated
          required: true
          schema:
            type: string
      requestBody:
        description: |
          resource
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AbstractDataEnvelope'
      responses:
        '200':
          description: DataEnvelope updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AbstractDataEnvelope'
        '404':
          description: |
            no DataEnvelope available for the given ID
        '500':
          $ref: '#/components/responses/defaultError'
    delete:
      description: |
        delete DataEnvelope
      operationId: deleteDataEnvelope
      parameters:
        - name: id
          in: path
          description: |
            ID of DataEnvelope to be deleted
          required: true
          schema:
            type: string
      responses:
        '204':
          description: DataEnvelope deleted
        '404':
          description: |
            no DataEnvelope available for the given id
        '500':
          $ref: '#/components/responses/defaultError'
  /dataenvelopes/search:
    post:
      description: |
        retrieve Id for existing DataEnvelope
      operationId: retrieveDataEnvelopeID
      requestBody:
        description: |
          DataEnvelope that should be matched
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AbstractDataEnvelope'
      responses:
        '200':
          description: |
                ok, matching existing DataEnvelope including identifier
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AbstractDataEnvelope'
        '500':
          $ref: '#/components/responses/defaultError'
  /dataenvelopes/explore:
    post:
      description: |
        query for existing DataEnvelopes
      operationId: queryExistingDataEnvelopes
      requestBody:
        description: |
          query parameters that should be matched
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataEnvelopeQuery'
      responses:
        '200':
          description: |
                list of matching DataEnvelopes, empty list if no match
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AbstractDataEnvelope'
        '500':
          $ref: '#/components/responses/defaultError'
  
components:
  schemas:
    AbstractDataEnvelope:
      $ref: './wacodis-schemas.yml#/components/schemas/AbstractDataEnvelope'
    SensorWebDataEnvelope:
      $ref: './wacodis-schemas.yml#/components/schemas/SensorWebDataEnvelope'
    CopernicusDataEnvelope:
      $ref: './wacodis-schemas.yml#/components/schemas/CopernicusDataEnvelope'
    GdiDeDataEnvelope:
      $ref: './wacodis-schemas.yml#/components/schemas/GdiDeDataEnvelope'
    WacodisProductDataEnvelope:
      $ref: './wacodis-schemas.yml#/components/schemas/WacodisProductDataEnvelope'
    AbstractResource:
      $ref: './wacodis-schemas.yml#/components/schemas/AbstractResource'
    PostResource:
      $ref: './wacodis-schemas.yml#/components/schemas/PostResource'
    GetResource:
      $ref: './wacodis-schemas.yml#/components/schemas/GetResource'
    AbstractSubsetDefinition:
      $ref: './wacodis-schemas.yml#/components/schemas/AbstractSubsetDefinition'
    SensorWebSubsetDefinition:
      $ref: './wacodis-schemas.yml#/components/schemas/SensorWebSubsetDefinition'
    CopernicusSubsetDefinition:
      $ref: './wacodis-schemas.yml#/components/schemas/CopernicusSubsetDefinition'
    CatalogueSubsetDefinition:
      $ref: './wacodis-schemas.yml#/components/schemas/CatalogueSubsetDefinition'
    DataAccessResourceSearchBody:
      $ref: './wacodis-schemas.yml#/components/schemas/DataAccessResourceSearchBody'
    AbstractBackend:
      $ref: './wacodis-schemas.yml#/components/schemas/AbstractBackend'
    ArcGISImageServerBackend:
      $ref: './wacodis-schemas.yml#/components/schemas/ArcGISImageServerBackend'
    GeoServerBackend:
      $ref: './wacodis-schemas.yml#/components/schemas/GeoServerBackend'
    DataEnvelopeQuery:
      $ref: './wacodis-schemas.yml#/components/schemas/DataEnvelopeQuery'
    Error:
      $ref: './wacodis-schemas.yml#/components/schemas/Error'
  responses:
    defaultError:
      description: |
        unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'