openapi: "3.0.0"
info:
  version: 0.1.0
  title: WaCoDiS JobDefinition API
  description: |
    The API for the WaCoDiS JobDefinitions
  termsOfService: https://wacodis.fbg-hsbo.de/
  contact:
    name: WaCoDiS Dev Team
    email: m.rieke@52north.org
    url: https://github.com/WaCoDiS
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost
paths:
  /jobDefinitions:
    get:
      description: |
        Returns a paginated list of WacodisJobDefinition
      operationId: retrieveWacodisJobDefinitions
      parameters:
        - $ref: '#/components/parameters/PagePage'
        - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          description: |
            WacodisJobDefinition response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedWacodisJobDefinitionResponse'
        '500':
          $ref: '#/components/responses/DefaultError'
    post:
      description: |
        Creates a new WacodisJobDefinition in the repository
      operationId: createWacodisJobDefinition
      requestBody:
        description: |
          WacodisJobDefinition to add to the repository
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WacodisJobDefinition'
      responses:
        '201':
          description: |
            WacodisJobDefinition response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WacodisJobDefinition'
          headers:
            Location:
              schema:
                type: string
              description: |
                the URL where to access the newly created WacodisJobDefinition
        '500':
          $ref: '#/components/responses/DefaultError'
  /jobDefinitions/{id}:
    get:
      description: |
        Returns a WacodisJobDefinition based on a single ID
      operationId: retrieveWacodisJobDefinitionById
      parameters:
        - name: id
          in: path
          description: |
            ID of WacodisJobDefinition to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: |
            WacodisJobDefinition response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WacodisJobDefinition'
        '500':
          $ref: '#/components/responses/DefaultError'
    delete:
      description: |
        deletes a single WacodisJobDefinition based on the ID supplied
      operationId: deleteWacodisJobDefinition
      parameters:
        - name: id
          in: path
          description: |
            ID of WacodisJobDefinition to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: |
            WacodisJobDefinition deleted
        '500':
          $ref: '#/components/responses/DefaultError'
    patch:
      description: |
        update a single WacodisJobDefinition based on the ID supplied
      operationId: updateWacodisJobDefinition
      parameters:
        - name: id
          in: path
          description: |
            ID of WacodisJobDefinition to be updated
          required: true
          schema:
            type: string
      requestBody:
        description: |
          WacodisJobDefinition to add to the repository
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WacodisJobDefinition'
      responses:
        '200':
          description: |
            updated WacodisJobDefinition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WacodisJobDefinition'
        '404':
          description: |
            no WacodisJobDefinition available for the given id
        '500':
          $ref: '#/components/responses/DefaultError'
components:
  schemas:
    PaginatedResponse:
      $ref: './wacodis-schemas.yml#/components/schemas/PaginatedResponse'
    PaginatedWacodisJobDefinitionResponse:
      $ref: './wacodis-schemas.yml#/components/schemas/PaginatedWacodisJobDefinitionResponse'
    WacodisJobDefinition:
      $ref: './wacodis-schemas.yml#/components/schemas/WacodisJobDefinition'
    AbstractSubsetDefinition:
      $ref: './wacodis-schemas.yml#/components/schemas/AbstractSubsetDefinition'
    SensorWebSubsetDefinition:
      $ref: './wacodis-schemas.yml#/components/schemas/SensorWebSubsetDefinition'
    CopernicusSubsetDefinition:
      $ref: './wacodis-schemas.yml#/components/schemas/CopernicusSubsetDefinition'
    CatalogueSubsetDefinition:
      $ref: './wacodis-schemas.yml#/components/schemas/CatalogueSubsetDefinition'
    Error:
      $ref: './wacodis-schemas.yml#/components/schemas/Error'
  parameters:
    PagePage:
      name: page
      in: query
      description: |
        the page as an offset (default=0)
      required: false
      schema:
        type: integer
        format: int32
    PageSize:
      name: size
      in: query
      description: |
        the maximum number of results (default=100)
      required: false
      schema:
        type: integer
        format: int32
  responses:
    DefaultError:
      description: |
        unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
